apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: memory
spec:
  tls:
    - hosts:
        - memory.berget.ai
      secretName: memory-tls
  rules:
    - host: memory.berget.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: memory
                port:
                  number: 80
