apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: memory
          env:
            - name: ENVIRONMENT
              value: "stage"
