apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memory

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: ssh-service-patch.yaml

images:
  - name: ghcr.io/berget-ai/memory
    newTag: 1.0.0-rc.0 # {"$imagepolicy": "flux-system:memory-stage:tag"}

labels:
  - pairs:
      environment: stage
    includeSelectors: false
