apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-memory-data
  namespace: memory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: harvester
